steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
artifacts:
  objects:
    location: 'gs://cloudbuild-mm/web/'
    paths: ['/workspace/target/*.jar']
- name: 'gcr.io/$PROJECT_ID/gsutil'
  args: ['ls']
