steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['tar', 'cvf', 'doc/', 'gs://cloudbuild-mm/web/doc.tar']
  waitFor: ['-']  # The '-' indicates that this step begins immediately.
  id: 'fetch-resources'
artifacts:
  objects:
    location: 'gs://cloudbuild-mm/web/'
    paths: ['/workspace/target/*.jar']
